[pytest]
pythonpath = .
testpaths = tests

# ❗ отключаем вывод логов в терминал
log_cli = false

# ❗ отключаем захват логов для allure (очень важно)
addopts = --allure-no-capture

markers = 
    smoke: быстрые критические тесты